In [1]:
import pandas as pd
import joblib
from pathlib import Path

In [2]:
BASE_DIR = Path.cwd()

voyage_df = pd.DataFrame(
    joblib.load(BASE_DIR / "debug/6Db1zZcoO7JPczkjjU4vuX" / "songs.pkl")
)

In [3]:
voyage_df.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,track_youtube_id
0,1B2wrYVrPtd3CcrYwUwmPE,"Justin Bieber, Brandon Love, Chandler Moore",Freedom.,All She Wrote (feat. Brandon Love & Chandler M...,38,234400,False,None,None,None,...,None,None,None,None,None,None,None,None,NaN,None
1,7ciVByPgRrzDHnSuLiQ7Ju,"Audiomarc, Nasty C",Audio Czzle (feat. Nasty C),Audio Czzle (feat. Nasty C),34,274000,True,None,None,None,...,None,None,None,None,None,None,None,None,NaN,None
2,21vc2kQZMS00cAyNT82a1M,"¥$, Kanye West, Ty Dolla $ign, Bump J",VULTURES,VULTURES,1,237534,True,None,None,None,...,None,None,None,None,None,None,None,None,NaN,None
3,24lORMRGMv9sXpZJdN1PVm,"Dreezy, 6LACK, Kodak Black",Spar (feat. 6LACK & Kodak Black),Spar (feat. 6LACK & Kodak Black),44,231194,True,None,None,None,...,None,None,None,None,None,None,None,None,NaN,None
4,5hzrmJKIS2CHmvlUWkdlYy,Joyner Lucas,Seventeen,Seventeen,51,205925,True,None,None,None,...,None,None,None,None,None,None,None,None,NaN,None

In [4]:
# Get IDs of all liked songs
liked_ids = list(voyage_df["track_id"].values)

In [5]:
# Load all songs to check how many in the taste vector are available
# Why -> Tast vector is missing all song features - We need to impute with known values

import joblib

songs_df = joblib.load("songs.pkl")

In [6]:
songs_df.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [7]:
liked_features = songs_df[songs_df["track_id"].isin(liked_ids)]
liked_features.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
2706,4ePKbzLwkIBslceokt2iXZ,The Seige,I Am Defiant,I Am Defiant,60,248880,True,0.477,0.859,6,-3.649,1,0.2640,0.09320,0.000000,0.710,0.504,125.044,4,alt-rock
28138,0ZPfoFzZ4qmdyzYmG8whmn,Krewella,zer0,Greenlights,53,162442,False,0.548,0.835,1,-5.094,1,0.0394,0.00874,0.000653,0.238,0.385,160.022,4,dub
29142,0ZPfoFzZ4qmdyzYmG8whmn,Krewella,zer0,Greenlights,53,162442,False,0.548,0.835,1,-5.094,1,0.0394,0.00874,0.000653,0.238,0.385,160.022,4,dubstep

In [8]:
# Extract numeric features
num_feat= liked_features.select_dtypes(include='number').columns.to_list()

In [9]:
# Import the model
model = joblib.load("model.pkl")

# Get predictions from numeric features in the taste vector
distances, indices = model.kneighbors(liked_features[num_feat])

In [12]:
indices

array([[36644, 13837, 45633,  8636, 22545, 74189, 37174, 64870, 53965,
        21629],
       [26492, 88129, 80055, 63324, 28142, 66291, 57845, 67277, 33695,
        89369],
       [26492, 88129, 80055, 63324, 28142, 66291, 57845, 67277, 33695,
        89369]])

In [16]:
recommendations = []
for i in indices:
    recommendations.extend(i)

In [17]:
songs_df.iloc[recommendations, :]

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
36644,4lsxE7TLiXz8n7E22yZayg,Starshooter,Starshooter [1er Album],Betsy Party - Remasterisé en 2010,32,193640,False,0.176,0.939,4,-5.363,1,0.0995,0.015500,0.009660,0.8490,0.553,188.798,4,french
13837,33N5h7nl3vxh6FGxIwSgxl,J.M. Silk,Hold on to Your Dream (Bonus Track Version),Shadows of Your Love,5,240733,False,0.657,0.900,6,-6.148,0,0.0374,0.033500,0.000115,0.1190,0.745,119.668,4,chicago-house
45633,59708AZI2d9mudYk1GPNlq,João Gilberto,João Gilberto (1973),Eu Quero Um Samba,24,286302,False,0.705,0.228,3,-15.747,1,0.0937,0.761000,0.000045,0.1200,0.482,175.904,4,guitar
8636,5mZ3SenUADr24QRqwA0Bt2,LJ Echols,Another level,From the Back,35,212546,False,0.849,0.803,5,-4.514,0,0.0616,0.074500,0.000035,0.0621,0.962,111.008,4,blues
22545,0t15FcXk7Ab1OWXVa1LdAL,Burgerkill,Adamantine,United Front,24,291196,True,0.503,0.964,7,-6.547,1,0.0938,0.000025,0.064900,0.3250,0.210,111.998,4,death-metal
74189,37i2AqYonqyW5MoGXCY0pG,Capital Inicial,Capital Inicial,Música Urbana - Versão Alternativa,47,211000,False,0.420,0.760,7,-5.021,1,0.0771,0.005600,0.000128,0.1090,0.801,172.947,4,mpb
37174,559NPMJR6VfISMfUR7Dv8v,Clean Bandit;A7S,New Pop Classics,Everything but You,0,198014,False,0.679,0.764,6,-5.301,1,0.0391,0.031000,0.000009,0.0951,0.471,124.977,4,funk
64870,0S4HB769BP3gdVWfe7SLtS,Nazan Öncel,Yan Yana Fotoğraf Çektirelim,Beyoğlu,39,222320,False,0.661,0.764,5,-6.572,0,0.0357,0.061300,0.000000,0.2610,0.637,114.949,4,jazz
53965,5XPo15e5ICs6NvSMn44pTF,Virginia To Vegas;NOTD,Malibu,Malibu,68,148822,True,0.657,0.653,9,-8.525,1,0.0258,0.056800,0.000142,0.3210,0.624,111.974,4,house
21629,4jiz1yjntTi04Kstn960LL,Vybz Kartel,The Gaza Don,Jump in the Benz,28,202536,False,0.758,0.664,4,-5.262,0,0.2670,0.185000,0.000000,0.3240,0.288,103.122,4,dancehall
26492,30IRW66PmyMMv207abFNe9,Doctora Juguetes;Felpita;Lambie,Doctora Juguetes: Ya Llegó la Doctora,Recarga Energía,22,46840,False,0.557,0.888,9,-3.847,1,0.2680,0.422000,0.000000,0.2610,0.751,71.627,4,disney
88129,0tWAW1X2zdHuDn70mRlNTE,KAROL G;Mariah Angeliq,El perreo es el futuro,EL MAKINON,0,209160,False,0.689,0.705,0,-3.224,0,0.1020,0.256000,0.000001,0.1080,0.456,89.109,4,reggae
80055,2L1OXzqVPpVxotHfLglUcB,Diljit Dosanjh;Tory Lanez;Ikky,Chauffeur,Chauffeur,71,205040,True,0.639,0.767,6,-4.997,1,0.0928,0.130000,0.000000,0.2050,0.540,154.032,4,pop-film
63324,2p8ji4NXTvYvAIRnK2d1kH,Fujifabric,FAB FOX,茜色の夕日,36,339493,False,0.553,0.546,7,-5.306,1,0.0263,0.082500,0.000016,0.0764,0.438,138.006,4,j-rock
28142,1nRHE3fyknlOsrW56oG53W,Miles Away;Exede,Miles Away,Clear,43,194877,False,0.577,0.790,10,-3.940,1,0.0311,0.484000,0.000005,0.0703,0.494,122.047,4,dub
66291,4btCr04tBy7IFEtOm5K2ZM,Mini Pop Kids,Mini Pop Kids 18,Holiday,14,169720,False,0.625,0.594,7,-5.279,1,0.0293,0.323000,0.000000,0.2300,0.609,104.041,4,kids
57845,53h5F3GuRlrclYdMrNGaDO,The Wombats,All Out Alternative,Let's Dance to Joy Division,0,191293,False,0.398,0.838,4,-6.679,1,0.1020,0.001270,0.000000,0.5760,0.747,116.913,4,indie
67277,7AhSY7tH8oT0T9FpRKXl9q,Jhayco,Halloween 2022 Perreo Vol. 4,No Me Conoce,1,240400,False,0.654,0.695,10,-3.987,0,0.1730,0.064300,0.000000,0.0980,0.582,81.153,1,latin
33695,2WetC8JAhHprkgIP4RXIki,Microwave,Much Love,Homebody,34,202146,False,0.596,0.886,1,-5.508,1,0.0296,0.000174,0.001010,0.2510,0.675,131.963,4,emo
89369,10kHKrWmrGJG1J9xO8HMDi,Don Omar;Zion & Lennox,Del gusto de hermanos,Te Quiero Pa´Mi,2,212026,False,0.765,0.816,1,-3.990,1,0.0595,0.124000,0.000082,0.1970,0.624,89.005,4,reggaeton
26492,30IRW66PmyMMv207abFNe9,Doctora Juguetes;Felpita;Lambie,Doctora Juguetes: Ya Llegó la Doctora,Recarga Energía,22,46840,False,0.557,0.888,9,-3.847,1,0.2680,0.422000,0.000000,0.2610,0.751,71.627,4,disney
88129,0tWAW1X2zdHuDn70mRlNTE,KAROL G;Mariah Angeliq,El perreo es el futuro,EL MAKINON,0,209160,False,0.689,0.705,0,-3.224,0,0.1020,0.256000,0.000001,0.1080,0.456,89.109,4,reggae
80055,2L1OXzqVPpVxotHfLglUcB,Diljit Dosanjh;Tory Lanez;Ikky,Chauffeur,Chauffeur,71,205040,True,0.639,0.767,6,-4.997,1,0.0928,0.130000,0.000000,0.2050,0.540,154.032,4,pop-film
63324,2p8ji4NXTvYvAIRnK2d1kH,Fujifabric,FAB FOX,茜色の夕日,36,339493,False,0.553,0.546,7,-5.306,1,0.0263,0.082500,0.000016,0.0764,0.438,138.006,4,j-rock
28142,1nRHE3fyknlOsrW56oG53W,Miles Away;Exede,Miles Away,Clear,43,194877,False,0.577,0.790,10,-3.940,1,0.0311,0.484000,0.000005,0.0703,0.494,122.047,4,dub
66291,4btCr04tBy7IFEtOm5K2ZM,Mini Pop Kids,Mini Pop Kids 18,Holiday,14,169720,False,0.625,0.594,7,-5.279,1,0.0293,0.323000,0.000000,0.2300,0.609,104.041,4,kids
57845,53h5F3GuRlrclYdMrNGaDO,The Wombats,All Out Alternative,Let's Dance to Joy Division,0,191293,False,0.398,0.838,4,-6.679,1,0.1020,0.001270,0.000000,0.5760,0.747,116.913,4,indie
67277,7AhSY7tH8oT0T9FpRKXl9q,Jhayco,Halloween 2022 Perreo Vol. 4,No Me Conoce,1,240400,False,0.654,0.695,10,-3.987,0,0.1730,0.064300,0.000000,0.0980,0.582,81.153,1,latin
33695,2WetC8JAhHprkgIP4RXIki,Microwave,Much Love,Homebody,34,202146,False,0.596,0.886,1,-5.508,1,0.0296,0.000174,0.001010,0.2510,0.675,131.963,4,emo
89369,10kHKrWmrGJG1J9xO8HMDi,Don Omar;Zion & Lennox,Del gusto de hermanos,Te Quiero Pa´Mi,2,212026,False,0.765,0.816,1,-3.990,1,0.0595,0.124000,0.000082,0.1970,0.624,89.005,4,reggaeton